# Generated by Django 3.2.3 on 2021-06-04 15:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(help_text='Razão Social da Empresa', max_length=40)),
                ('cnpj', models.CharField(max_length=18)),
                ('data_cadastro', models.DateField(default=datetime.datetime(2021, 6, 4, 15, 6, 33, 996348, tzinfo=utc))),
                ('endereco', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=14)),
                ('phone', models.CharField(max_length=10)),
                ('status', models.BooleanField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1)),
                ('responsavel', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
