# Generated by Django 3.2.4 on 2021-06-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210604_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.BooleanField(blank=True, choices=[(0, 'Inativo'), (1, 'Ativo')], default=1),
        ),
    ]
