# Generated by Django 3.2.4 on 2021-06-04 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_auto_20210604_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='responsavel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.BooleanField(blank=True, choices=[(1, 'Ativo'), (0, 'Inativo')], default=1),
        ),
    ]
