# Generated by Django 3.2.3 on 2021-06-04 14:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0003_alter_clientedados_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClienteDados',
            new_name='Collaborator',
        ),
    ]
